# Generated by Django 5.1.7 on 2025-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='coarsecode',
            field=models.CharField(default='SM000', max_length=100),
        ),
    ]
